#!/bin/sh
# Aegis local development helper (POSIX sh; works on macOS and Linux).
#
# Default (no flags): starts public/downloads/aegis_collector.py on
# 127.0.0.1:8931 with freshly generated demo credentials, writes a frontend
# .env.local pointing at it, and seeds 5 demo device reports with curl.
#
# Usage:
#   scripts/dev-collector.sh           start collector + seed demo data
#   scripts/dev-collector.sh --seed    seed demo data into a running collector
#   scripts/dev-collector.sh --stop    stop the background collector
#   scripts/dev-collector.sh --help    show this help
set -eu

usage() {
    cat <<'USAGE'
Usage: scripts/dev-collector.sh [--seed | --stop | --help]

  (no args)  Start the Aegis collector on 127.0.0.1:8931 with demo
             credentials, write .env.local for the frontend, and seed
             5 demo device reports.
  --seed     Seed 5 demo device reports into an already running collector
             (uses the credentials stored in .dev/collector.env).
  --stop     Stop the background collector started by this script.
  --help     Show this help.

State lives in .dev/ (gitignored): collector DB, log, PID file, and the
generated demo credentials.
USAGE
}

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
COLLECTOR_PY="$ROOT/public/downloads/aegis_collector.py"
DEV_DIR="$ROOT/.dev"
CRED_FILE="$DEV_DIR/collector.env"
PID_FILE="$DEV_DIR/collector.pid"
LOG_FILE="$DEV_DIR/collector.log"
DB_FILE="$DEV_DIR/aegis-collector.db"
ENV_LOCAL="$ROOT/.env.local"
HOST=127.0.0.1
PORT=${AEGIS_DEV_COLLECTOR_PORT:-8931}
BASE_URL="http://$HOST:$PORT"
TMP_DIR=""

cleanup() {
    if [ -n "$TMP_DIR" ] && [ -d "$TMP_DIR" ]; then
        rm -rf "$TMP_DIR"
    fi
}
trap cleanup EXIT INT TERM

die() {
    printf 'error: %s\n' "$1" >&2
    exit 1
}

need() {
    command -v "$1" >/dev/null 2>&1 || die "'$1' is required but was not found in PATH"
}

gen_secret() {
    # 64-char lowercase hex (256 bits)
    python3 -c 'import secrets; print(secrets.token_hex(32))'
}

collector_pid() {
    if [ -f "$PID_FILE" ]; then
        pid=$(cat "$PID_FILE" 2>/dev/null || true)
        if [ -n "${pid:-}" ] && kill -0 "$pid" 2>/dev/null; then
            printf '%s' "$pid"
            return 0
        fi
    fi
    return 1
}

wait_healthy() {
    tries=0
    while [ "$tries" -lt 30 ]; do
        if curl -fsS -o /dev/null "$BASE_URL/health" 2>/dev/null; then
            return 0
        fi
        if ! collector_pid >/dev/null; then
            printf 'collector exited during startup; last log lines:\n' >&2
            tail -n 20 "$LOG_FILE" >&2 || true
            die "collector failed to start"
        fi
        tries=$((tries + 1))
        sleep 1
    done
    die "collector did not become healthy at $BASE_URL/health within 30s"
}

load_or_create_credentials() {
    need python3
    mkdir -p "$DEV_DIR"
    if [ -f "$CRED_FILE" ]; then
        # shellcheck disable=SC1090
        . "$CRED_FILE"
        DEV_TOKEN=$AEGIS_COLLECTOR_TOKEN
        DEV_SIGNING_SECRET=$AEGIS_REPORT_SIGNING_SECRET
    else
        DEV_TOKEN=$(gen_secret)
        DEV_SIGNING_SECRET=$(gen_secret)
        (
            umask 077
            cat > "$CRED_FILE" <<EOF
# Demo-only credentials generated by scripts/dev-collector.sh. Never commit.
AEGIS_COLLECTOR_TOKEN=$DEV_TOKEN
AEGIS_REPORT_SIGNING_SECRET=$DEV_SIGNING_SECRET
EOF
        )
        printf 'generated demo credentials in %s\n' "$CRED_FILE"
    fi
}

write_env_local() {
    cat > "$ENV_LOCAL" <<EOF
AEGIS_COLLECTOR_URL=http://127.0.0.1:$PORT
AEGIS_COLLECTOR_ALLOWED_HOST=$HOST
AEGIS_COLLECTOR_TOKEN=$DEV_TOKEN
EOF
    printf 'wrote %s\n' "$ENV_LOCAL"
}

start_collector() {
    [ -f "$COLLECTOR_PY" ] || die "missing $COLLECTOR_PY"
    if pid=$(collector_pid); then
        printf 'collector already running (pid %s) at %s\n' "$pid" "$BASE_URL"
        return 0
    fi
    mkdir -p "$DEV_DIR"
    AEGIS_COLLECTOR_TOKEN=$DEV_TOKEN \
    AEGIS_REPORT_SIGNING_SECRET=$DEV_SIGNING_SECRET \
    AEGIS_REQUESTS_PER_MINUTE=600 \
    AEGIS_REQUIRED_AGENT_VERSION=0.30.0 \
    AEGIS_REQUIRED_POLICY_VERSION=4.8.0 \
    nohup python3 "$COLLECTOR_PY" --listen "$HOST" --port "$PORT" --db "$DB_FILE" \
        >> "$LOG_FILE" 2>&1 &
    printf '%s\n' "$!" > "$PID_FILE"
    printf 'started collector (pid %s) at %s, log: %s\n' "$(cat "$PID_FILE")" "$BASE_URL" "$LOG_FILE"
    wait_healthy
    printf 'collector health check passed\n'
}

post_report_body() {
    # $1: path to a file holding the exact JSON report body.
    body_file=$1
    ts=$(date +%s)
    { printf '%s.' "$ts"; cat "$body_file"; } > "$TMP_DIR/signed.bin"
    sig=$(openssl dgst -sha256 -hmac "$DEV_SIGNING_SECRET" "$TMP_DIR/signed.bin" | awk '{print $NF}')
    status=$(curl -s -o "$TMP_DIR/response.json" -w '%{http_code}' \
        -X POST "$BASE_URL/v1/reports" \
        -H "Authorization: Bearer $DEV_TOKEN" \
        -H "Content-Type: application/json" \
        -H "X-Aegis-Timestamp: $ts" \
        -H "X-Aegis-Signature: sha256=$sig" \
        --data-binary "@$body_file")
    case "$status" in
        200|202)
            device=$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["device_id"])' "$body_file")
            printf 'seeded report for %s (HTTP %s)\n' "$device" "$status"
            ;;
        *)
            cat "$TMP_DIR/response.json" >&2 || true
            die "collector rejected a demo report (HTTP $status)"
            ;;
    esac
}

seed_demo_reports() {
    need curl
    need openssl
    TMP_DIR=$(mktemp -d)
    now=$(date +%s)

    cat > "$TMP_DIR/report1.json" <<EOF
{"schema":"aegis.report/v1","agent_version":"0.30.0","policy_version":"4.8.0","device_id":"ENG-MBP-0142","scanned_at":$now,"scan_root":"/Users/demo.eng","summary":{"critical":1,"high":1,"medium":1,"low":0},"findings":[{"kind":"unsigned_skill_install","severity":"critical","path":"/Users/demo.eng/.cursor/skills/deploy-helper","message":"Skill executes curl | sh from an unverified third-party source","evidence":"install.sh fetched from non-allowlisted host"},{"kind":"stale_mcp_config","severity":"high","path":"/Users/demo.eng/.codeium/windsurf/mcp_config.json","message":"MCP server pinned to a version with a known command-injection advisory"},{"kind":"dev_tool_detected","severity":"medium","path":"/Applications/Cursor.app","message":"Unmanaged AI coding tool discovered on engineering laptop"}],"inventory":[{"category":"tool","name":"Cursor","version":"1.4.2"},{"category":"mcp_server","name":"github","status":"enabled"}]}
EOF

    cat > "$TMP_DIR/report2.json" <<EOF
{"schema":"aegis.report/v1","agent_version":"0.28.1","policy_version":"4.6.0","device_id":"MKT-LT-0287","scanned_at":$now,"scan_root":"/Users/demo.mkt","summary":{"critical":0,"high":1,"medium":0,"low":1},"findings":[{"kind":"outdated_agent","severity":"high","path":"/usr/local/bin/aegis-agent","message":"Agent 0.28.1 is behind the required baseline 0.30.0"},{"kind":"informational_scan","severity":"low","path":"/Users/demo.mkt","message":"Routine scan completed with no policy violations"}],"inventory":[{"category":"tool","name":"Claude Code","version":"0.2.9"}]}
EOF

    cat > "$TMP_DIR/report3.json" <<EOF
{"schema":"aegis.report/v1","agent_version":"0.30.0","policy_version":"4.8.0","device_id":"OPS-WIN-0533","scanned_at":$now,"scan_root":"C:\\\\Users\\\\demo.ops","summary":{"critical":0,"high":0,"medium":1,"low":1},"findings":[{"kind":"world_readable_config","severity":"medium","path":"C:\\\\Users\\\\demo.ops\\\\.codex\\\\config.json","message":"Codex CLI configuration is readable by all local users"},{"kind":"informational_scan","severity":"low","path":"C:\\\\Users\\\\demo.ops","message":"No unsigned skills detected in this scan window"}],"inventory":[{"category":"tool","name":"Codex CLI","version":"0.9.1"},{"category":"skill","name":"release-notes","source":"marketplace","signature":"verified"}]}
EOF

    cat > "$TMP_DIR/report4.json" <<EOF
{"schema":"aegis.report/v1","agent_version":"0.30.0","policy_version":"4.8.0","device_id":"ENG-MBP-0915","scanned_at":$now,"scan_root":"/Users/demo.eng2","summary":{"critical":0,"high":0,"medium":0,"low":1},"findings":[{"kind":"informational_scan","severity":"low","path":"/Users/demo.eng2","message":"Compliant workstation; agent and policy versions current"}],"inventory":[{"category":"tool","name":"Windsurf","version":"1.3.0"},{"category":"mcp_server","name":"filesystem","status":"enabled"}]}
EOF

    cat > "$TMP_DIR/report5.json" <<EOF
{"schema":"aegis.report/v1","agent_version":"0.26.4","policy_version":"4.2.1","device_id":"MKT-LT-0466","scanned_at":$now,"scan_root":"/Users/demo.mkt2","summary":{"critical":1,"high":0,"medium":1,"low":0},"findings":[{"kind":"secret_in_mcp_config","severity":"critical","path":"/Users/demo.mkt2/.claude/mcp.json","message":"Plaintext API credential committed inside an MCP server configuration","evidence":"key redacted; pattern matched known vendor prefix"},{"kind":"dev_tool_detected","severity":"medium","path":"/Users/demo.mkt2/Applications/Claude Code","message":"AI coding tool installed outside managed software channel"}],"inventory":[{"category":"tool","name":"Claude Code","version":"0.1.8"},{"category":"tool","name":"Cursor","version":"1.2.7"}]}
EOF

    for body in "$TMP_DIR"/report1.json "$TMP_DIR"/report2.json "$TMP_DIR"/report3.json "$TMP_DIR"/report4.json "$TMP_DIR"/report5.json; do
        post_report_body "$body"
    done
    printf 'seeded 5 demo device reports\n'
}

stop_collector() {
    if pid=$(collector_pid); then
        kill "$pid" 2>/dev/null || true
        tries=0
        while [ "$tries" -lt 10 ] && kill -0 "$pid" 2>/dev/null; do
            sleep 1
            tries=$((tries + 1))
        done
        if kill -0 "$pid" 2>/dev/null; then
            kill -9 "$pid" 2>/dev/null || true
        fi
        rm -f "$PID_FILE"
        printf 'stopped collector (pid %s)\n' "$pid"
    else
        rm -f "$PID_FILE"
        printf 'collector is not running\n'
    fi
}

print_instructions() {
    cat <<EOF

Next steps:
  1. Install frontend dependencies (first time only):
       npm install
  2. Start the console dev server:
       npm run dev
  3. Open http://localhost:3000 -- the console reads .env.local and
     proxies fleet data from the collector at $BASE_URL

Useful commands:
  Tail collector log:        tail -f .dev/collector.log
  Seed 5 more demo reports:  scripts/dev-collector.sh --seed
  Seed a larger demo fleet:  python3 scripts/seed-demo-reports.py --collector-url $BASE_URL --token <token in .dev/collector.env>
  Stop the collector:        scripts/dev-collector.sh --stop
EOF
}

mode=start
case "${1:-}" in
    --stop) mode=stop ;;
    --seed) mode=seed ;;
    --help|-h) usage; exit 0 ;;
    "") ;;
    *) usage >&2; die "unknown argument: $1" ;;
esac

case "$mode" in
    start)
        need python3
        need curl
        need openssl
        load_or_create_credentials
        write_env_local
        start_collector
        seed_demo_reports
        print_instructions
        ;;
    seed)
        [ -f "$CRED_FILE" ] || die "no demo credentials found at $CRED_FILE; run 'scripts/dev-collector.sh' once to start the collector first"
        load_or_create_credentials
        curl -fsS -o /dev/null "$BASE_URL/health" || die "collector is not reachable at $BASE_URL/health; run 'scripts/dev-collector.sh' to start it"
        seed_demo_reports
        ;;
    stop)
        stop_collector
        ;;
esac
